export const MODEL_VERSION = 1;

export const ACTIONS = [
  "advance",
  "retreat",
  "strafe_left",
  "strafe_right",
  "light_attack",
  "heavy_attack",
  "block",
  "wait",
  "punish_dodge",
  "delay_attack",
  "feint",
  "bait_parry",
];

export const HIT_SLASH_STYLES = ["diag_tl_br", "diag_tr_bl", "vertical_center"];

export const MAZE_CONFIG = {
  baseSize: 15,
  growthStep: 2,
  maxSize: 41,
  baseEnemyCount: 4,
  maxEnemyCount: 30,
};

export const BOSS_PART_MODELS = {
  heads: [
    { id: "war_skull", headSize: 0.31, jawWidth: 0.42, browDepth: 0.13 },
    { id: "crown_horn", headSize: 0.34, jawWidth: 0.37, browDepth: 0.15 },
    { id: "plated_howl", headSize: 0.3, jawWidth: 0.4, browDepth: 0.12 },
    { id: "fang_mantle", headSize: 0.33, jawWidth: 0.44, browDepth: 0.11 },
    { id: "grim_mask", headSize: 0.29, jawWidth: 0.35, browDepth: 0.16 },
  ],
  torsos: [
    { id: "fortress_core", bodyWidth: 0.62, shoulderWidth: 0.86, armorRig: "heavy_slab", bladeScale: 1.48, bobAmp: 0.48 },
    { id: "spine_plating", bodyWidth: 0.58, shoulderWidth: 0.8, armorRig: "lamellar_guard", bladeScale: 1.44, bobAmp: 0.52 },
    { id: "crusher_harness", bodyWidth: 0.64, shoulderWidth: 0.88, armorRig: "heavy_slab", bladeScale: 1.56, bobAmp: 0.44 },
    { id: "warden_cuirass", bodyWidth: 0.57, shoulderWidth: 0.79, armorRig: "high_guard_plate", bladeScale: 1.42, bobAmp: 0.49 },
    { id: "chain_bulwark", bodyWidth: 0.61, shoulderWidth: 0.84, armorRig: "strap_and_spike", bladeScale: 1.5, bobAmp: 0.46 },
  ],
  legs: [
    { id: "pillar_legs", legLift: 0.25, stance: 0.56 },
    { id: "anvil_stride", legLift: 0.22, stance: 0.58 },
    { id: "raider_stride", legLift: 0.29, stance: 0.54 },
    { id: "wall_knees", legLift: 0.24, stance: 0.6 },
    { id: "siege_tread", legLift: 0.21, stance: 0.62 },
  ],
};

export const BOSS_NAME_TABLE = [
  ["Bolgrod", "Bone", "Crusher"],
  ["Mordrath", "Skull", "Breaker"],
  ["Kargul", "Iron", "Render"],
  ["Throzak", "Grave", "Shatterer"],
  ["Vorgath", "Ruin", "Severer"],
  ["Drakmor", "Wound", "Grinder"],
  ["Gorvul", "Flesh", "Ravager"],
  ["Ulkrad", "Ash", "Burner"],
  ["Zargoth", "Chain", "Ripper"],
  ["Grumvek", "Stone", "Sunderer"],
];

export const SHOP_ITEMS = [
  {
    id: "helm_ironwatch",
    name: "Ironwatch Helm",
    kind: "head_armor",
    rarity: "uncommon",
    goldCost: 85,
    tokenCost: 0,
    desc: "Helmet plate with a narrow visor slot.",
    statText: "Damage taken x0.97",
    sellGold: 45,
    stackable: false,
  },
  {
    id: "chest_reinforced",
    name: "Reinforced Chestplate",
    kind: "torso_armor",
    rarity: "rare",
    goldCost: 140,
    tokenCost: 0,
    desc: "Arms and chest armor with shock-rib lining.",
    statText: "Damage taken x0.94",
    sellGold: 72,
    stackable: false,
  },
  {
    id: "greaves_bastion",
    name: "Bastion Greaves",
    kind: "leg_armor",
    rarity: "rare",
    goldCost: 135,
    tokenCost: 0,
    desc: "Weighted lower armor for grounded dodges.",
    statText: "Dash stamina cost x0.9",
    sellGold: 68,
    stackable: false,
  },
  {
    id: "sword_skin_torque",
    name: "Torque Blade Skin",
    kind: "weapon_skin",
    rarity: "very-rare",
    goldCost: 210,
    tokenCost: 0,
    desc: "Industrial steel skin with bright edge highlights.",
    statText: "Cosmetic",
    sellGold: 105,
    stackable: false,
  },
  {
    id: "weapon_rift_cutter",
    name: "Rift Cutter",
    kind: "weapon",
    rarity: "exotic",
    goldCost: 310,
    tokenCost: 1,
    desc: "High-mass blade tuned for heavy strikes.",
    statText: "Heavy damage x1.1",
    sellGold: 155,
    stackable: false,
  },
  {
    id: "trail_ember_arc",
    name: "Ember Arc Trail",
    kind: "trail_cosmetic",
    rarity: "uncommon",
    goldCost: 95,
    tokenCost: 0,
    desc: "Adds a warmer slash trail accent.",
    statText: "Cosmetic",
    sellGold: 46,
    stackable: false,
  },
  {
    id: "health_potion",
    name: "Health Potion",
    kind: "potion_health",
    rarity: "common",
    goldCost: 38,
    tokenCost: 0,
    desc: "Restores 45 health when used (Key 1).",
    statText: "Stackable",
    sellGold: 19,
    stackable: true,
  },
  {
    id: "stamina_potion",
    name: "Stamina Potion",
    kind: "potion_stamina",
    rarity: "common",
    goldCost: 34,
    tokenCost: 0,
    desc: "Restores 55 stamina when used (Key 2).",
    statText: "Stackable",
    sellGold: 17,
    stackable: true,
  },
  {
    id: "mana_potion",
    name: "Mana Potion",
    kind: "potion_mana",
    rarity: "common",
    goldCost: 32,
    tokenCost: 0,
    desc: "Restores 40 mana when used (Key 3).",
    statText: "Stackable",
    sellGold: 16,
    stackable: true,
  },
  {
    id: "relic_bosscore",
    name: "Bosscore Reliquary",
    kind: "token_relic",
    rarity: "legendary",
    goldCost: 280,
    tokenCost: 5,
    desc: "Ancient relic traded for multiple boss tokens.",
    statText: "Damage x1.15, stamina cost x0.9",
    sellGold: 180,
    stackable: false,
  },
];

export const SHOP_BANTER_LINES = [
  "\"Buy quick. The arena's hungry.\"",
  "\"You look breakable. Armor helps.\"",
  "\"Specials cost tokens. Bring heads, not excuses.\"",
  "\"Need potions? Keep your blood inside you.\"",
  "\"Sell me your scraps. I'll call them antiques.\"",
];

export const ENEMY_SHAPE_LIBRARY = {
  balanced_duelist: {
    shapeId: "duelist_frame",
    armorRig: "lamellar_guard",
    bodyWidth: 0.36,
    shoulderWidth: 0.5,
    headSize: 0.22,
    bladeScale: 1,
    bobAmp: 0.9,
    jawWidth: 0.33,
    browDepth: 0.08,
  },
  aggressive_rusher: {
    shapeId: "rusher_frame",
    armorRig: "strap_and_spike",
    bodyWidth: 0.31,
    shoulderWidth: 0.46,
    headSize: 0.21,
    bladeScale: 1.08,
    bobAmp: 1.1,
    jawWidth: 0.35,
    browDepth: 0.09,
  },
  defensive_counterfighter: {
    shapeId: "counter_frame",
    armorRig: "high_guard_plate",
    bodyWidth: 0.35,
    shoulderWidth: 0.53,
    headSize: 0.21,
    bladeScale: 0.98,
    bobAmp: 0.84,
    jawWidth: 0.3,
    browDepth: 0.075,
  },
  heavy_brute: {
    shapeId: "brute_frame",
    armorRig: "heavy_slab",
    bodyWidth: 0.45,
    shoulderWidth: 0.6,
    headSize: 0.2,
    bladeScale: 1.24,
    bobAmp: 0.62,
    jawWidth: 0.4,
    browDepth: 0.1,
  },
};

export const ARCHETYPES = {
  balanced_duelist: {
    label: "Balanced Duelist",
    hp: 70,
    speed: 2.05,
    reactionDelay: 0.28,
    alpha: 0.11,
    gamma: 0.9,
    epsilon: 0.5,
    minEpsilon: 0.11,
    epsilonDecay: 0.992,
    aggressionClamp: [0.28, 0.78],
    actionBias: {
      advance: 0.14,
      retreat: 0.08,
      strafe_left: 0.14,
      strafe_right: 0.14,
      light_attack: 0.25,
      heavy_attack: 0.12,
      block: 0.2,
      wait: 0.08,
      punish_dodge: 0.16,
      delay_attack: 0.16,
      feint: 0.15,
      bait_parry: 0.12,
    },
    color: "#70d7ff",
  },
  aggressive_rusher: {
    label: "Aggressive Rusher",
    hp: 64,
    speed: 2.35,
    reactionDelay: 0.24,
    alpha: 0.1,
    gamma: 0.9,
    epsilon: 0.56,
    minEpsilon: 0.12,
    epsilonDecay: 0.993,
    aggressionClamp: [0.4, 0.92],
    actionBias: {
      advance: 0.4,
      retreat: -0.1,
      strafe_left: 0.15,
      strafe_right: 0.15,
      light_attack: 0.34,
      heavy_attack: 0.2,
      block: 0.02,
      wait: -0.2,
      punish_dodge: 0.24,
      delay_attack: 0.09,
      feint: 0.06,
      bait_parry: 0,
    },
    color: "#ff6a6a",
  },
  defensive_counterfighter: {
    label: "Defensive Counterfighter",
    hp: 74,
    speed: 1.95,
    reactionDelay: 0.31,
    alpha: 0.1,
    gamma: 0.91,
    epsilon: 0.49,
    minEpsilon: 0.09,
    epsilonDecay: 0.992,
    aggressionClamp: [0.22, 0.69],
    actionBias: {
      advance: 0.05,
      retreat: 0.24,
      strafe_left: 0.2,
      strafe_right: 0.2,
      light_attack: 0.15,
      heavy_attack: 0.09,
      block: 0.35,
      wait: 0.14,
      punish_dodge: 0.34,
      delay_attack: 0.18,
      feint: 0.2,
      bait_parry: 0.26,
    },
    color: "#9dc8ff",
  },
  heavy_brute: {
    label: "Heavy Brute",
    hp: 110,
    speed: 1.55,
    reactionDelay: 0.36,
    alpha: 0.085,
    gamma: 0.88,
    epsilon: 0.47,
    minEpsilon: 0.1,
    epsilonDecay: 0.993,
    aggressionClamp: [0.33, 0.82],
    actionBias: {
      advance: 0.28,
      retreat: -0.06,
      strafe_left: 0.03,
      strafe_right: 0.03,
      light_attack: 0.12,
      heavy_attack: 0.38,
      block: 0.1,
      wait: 0.11,
      punish_dodge: 0.23,
      delay_attack: 0.21,
      feint: 0.05,
      bait_parry: 0.01,
    },
    color: "#e8c27f",
  },
};

export const ATTACK_DEFS = {
  light: {
    staminaCost: 12,
    cooldown: 0.36,
    windup: 0.06,
    active: 0.11,
    recovery: 0.2,
    damage: 14,
    range: 1.15,
    arc: 0.85,
  },
  heavy: {
    staminaCost: 24,
    cooldown: 0.78,
    windup: 0.15,
    active: 0.14,
    recovery: 0.35,
    damage: 28,
    range: 1.32,
    arc: 0.96,
  },
};

export const ENEMY_ATTACK_DEFS = {
  light: {
    windup: 0.17,
    damage: 12,
    range: 1.08,
    arc: 0.95,
    cooldown: 0.68,
  },
  heavy: {
    windup: 0.31,
    damage: 22,
    range: 1.22,
    arc: 1.04,
    cooldown: 1.08,
  },
};
